import React from 'react'
import Head from "next/head"
import Link from "next/link"

function Error() {
  return (
    <>
     <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/unsplash_BsYD6CP0uEw.png" />
      </Head>
     <div style={{backgroundImage:'url("/unsplash_4ycv3Ky1ZZU.png")',backgroundSize:'cover',backgroundRepeat:'no-repeat'}} className="h-[200px] text-white flex flex-col items-center justify-center" >
        <h1 className="text-3xl font-bold mb-[10px]">404 Error</h1>
        <p className='text-[#195A00] '>404</p>
    </div>

    <div className="flex items-center justify-center h-[400px]">

        <div className='flex flex-col items-center justify-center'>
            <h2 className="text-5xl font-bold text-green-700 text-center mb-[40px]">404</h2>
            <h3 className="text-2xl font-bold text-center mb-[16px]">Oops! Look like something is going wrong </h3>
            <p className='w-[450px] text-center'>Page Cannot be Found we will figure out  in no time. Meanwhile check out fresh pages ideas.</p>
            <div className='mt-[30px] flex gap-[20px]'>
            <Link href="/"><button className="bg-[#195A00] text-white p-2 rounded-md w-[150px]">Go to home</button> </Link>
          </div>
        </div>

    </div>
    </>
  )
}

export default Error
