import Head from 'next/head'
import Image from 'next/image'
import { ReadableStreamDefaultController } from 'node:stream/web'
import styles from '../styles/Home.module.css'

export default function Home() {

  interface Food{
    image:string,
    item:string,
    name:string
  }
  interface Coffee{
    coffe:Food
  }


  const foods:Food[] = [
    {
      image:"/Mask Group (8).png",
      item:"23 item",
      name:"Grand Itano"
    },
    {
      image:"/Mask Group (6).png",
      item:"23 item",
      name:"Grand Itano"
    },
    {
      image:"/Mask Group (7).png",
      item:"23 item",
      name:"Grand Itano"
    },
    {
      image:"/Mask Group (5).png",
      item:"23 item",
      name:"Grand Itano"
    }
  ]

  const coffee = [
    {
     
      item:"Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibh",
      name:"Cappucino"
  },
  {
    
    item:"Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibh",
    name:"Cafe late"
},
{
  item:"Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibh",
  name:"Dark coffee"
}
]

const members = [
  {
    name:"Mary Henry",
    pos:"CEO",
    image:'/unsplash_llcX9pTjhXM.png'
  },
  {
    name:"Mary Henry",
    pos:"CEO",
    image:'/unsplash_EHK-EH1SRzQ.png'
  },
  {
    name:"Mary Henry",
    pos:"CEO",
    image:'/unsplash_llcX9pTjhXM.png'
  },
  {
    name:"Mary Henry",
    pos:"CEO",
    image:'/unsplash_EHK-EH1SRzQ.png'
  }
]

const menu = [
  {
    name:"Alder Grilled Chinook Salmon",
    desc:"Toasted French brand chopped chedical 500 Cal",
    price:"$32"
  },
  {
    name:"Alder Grilled Chinook Salmon",
    desc:"Toasted French brand chopped chedical 500 Cal",
    price:"$32"
  },
  {
    name:"Alder Grilled Chinook Salmon",
    desc:"Toasted French brand chopped chedical 500 Cal",
    price:"$32"
  },
  {
    name:"Alder Grilled Chinook Salmon",
    desc:"Toasted French brand chopped chedical 500 Cal",
    price:"$32"
  }
]
  return (
    <>
      <Head>
        <title>FoodTuck -Its quick & amusing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/unsplash_BsYD6CP0uEw.png" />
      </Head>

      <header className='relative flex justify-between items-center flex-col lg:flex-row'>
        <div className='md:ml-[150px] px-3'>
          <div><p className='text-[#195A00] mb-[15px] '>Its quick and amusing</p></div>
          <div><h1 className='font-bold text-5xl mb-[30px]'><span className='text-[#195A00] '>The</span> Art of Healthy life <br/>& Testy Food</h1>
          <p className=' md:placeholder:w-[550px] mt-[20px]'>Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhLoreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhr sit amet, consectur adipiscing elit. Leo augue nibh</p>
          <div className='mt-[30px] flex gap-[20px]'>
            <button className="bg-[#195A00] text-white p-2 rounded-md w-[150px]">Show More</button> <button className="w-[150px] border-[1px] border-[#195A00] rounded-md">Place Order</button>
          </div>
          </div>
        </div>
        <div className='relative mt-[50px] md:mt-0'>
          <Image src="/Bg (1).png" width={1600} height={200} alt="icon"/>
          <div className='absolute -left-[10px] bottom-[80px] rotate-180'>
            <Image src="/Image (1).png" width={530} height={300} alt="icon"/>
          </div>

        </div>
      </header>



      <div className="mt-[100px] flex items-center justify-center">

        <div className="flex justify-around items-center gap-[100px] flex-col-reverse px-3 md:flex-row">
          <div>
          <Image src="/Images.png" width={500} height={300} alt="icon"/>
          </div>
          <div>
            <h3>About Us</h3>
            <div>
              <h1 className="font-bold text-3xl mt-[20px]">Food is an Important <br/>part Of a balanced Diet</h1>
              <p className=' md:w-[450px] mt-[20px]'>Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhLoreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhr sit amet, consectur adipiscing elit. Leo augue nibh</p>

              <div className='mt-[30px] flex gap-[20px]'>
            <button className="bg-[#195A00] text-white p-2 rounded-md w-[150px]">Show More</button>
          </div>
            </div>
          </div>
        </div>
      </div>


      <div className="mt-[100px] flex items-center justify-center">

<div className="flex justify-around items-center gap-[100px] flex-col-reverse px-3 md:flex-row">
  <div>
  <Image src="/Imagess.png" width={500} height={300} alt="icon"/>
  </div>
  <div>
  <div>
              <h1 className="font-bold text-3xl mt-[20px]">We are also the best <br/>quality Coffee maker</h1>
              <p className=' md:w-[450px] mt-[20px]'>Loreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhLoreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhr sit amet, consectur adipiscing elit. Leo augue nibh</p>

              <div>
              <ul className="flex gap-[10px] text-black text-sm  flex-col mt-[30px]">
            <li className=' '>
             - Experienced chefs
            </li>
            <li>
             - Fresh and Organic Foods
            </li>
            <li>
            - Different Coffee & Drinks
            </li>
           
          </ul>
              </div>
              <div className='mt-[30px] flex gap-[20px]'>
            <button className="bg-[#195A00] text-white p-2 rounded-md w-[150px]">Learn More</button>
          </div>
            </div>
  </div>
</div>
</div>


<div className="relative h-[350px]">
  <div className='absolute left-0 top-0'>
  <Image src="/unsplash_Wu0MmDYdUB4.png" width={200} height={300} alt="icon"/>
  </div>
</div>


<div className='flex items-center justify-center -mt-[80px]'>
  <div>
    <div>
      <h1 className='text-center mb-[20px] font-bold text-3xl'>Food Category</h1>
    </div>

    <div className='grid grid-cols-2 md:grid-cols-4 gap-[20px]'>
      {
        foods.map((item:Food,index)=>{
          return(
            <div key={index} className="flex items-center justify-center flex-col">
              <Image src={item.image} width={230} height={100} alt="icon"/>
              <div className="flex items-center justify-center flex-col">
                <h3 className="">{item.name}</h3>
                <p className='text-sm mt-[5px] '>{item.item}</p>
              </div>
            </div>
          )
        })
      }
    </div>
  </div>
</div>



<div className='flex items-center justify-center mt-[120px]'>
  <div>
    <div>
      <h1 className='text-center mb-[20px] font-bold text-3xl'>Coffee Category</h1>
    </div>

    <div className='flex gap-[20px] flex-col md:flex-row'>

    <div>

    <div className='grid grid-cols-1 gap-[20px]'>
      {
        coffee.map((item,index)=>{
          return(
            <div key={index} className="flex items-center justify-center flex-col">
             
              <div className="flex  flex-col">
                <h3 className="text-2xl">{item.name}</h3>
                <p className='text-sm mt-[5px] w-[300px] '>{item.item}</p>
              </div>
            </div>
          )
        })
      }
    </div>

    </div>
    <div>
    <Image src="/unsplash_BsYD6CP0uEw.png" width={230} height={100} alt="icon"/>
    </div>



    <div>
    <div className='grid grid-cols-1 gap-[20px]'>
      {
        coffee.map((item,index)=>{
          return(
            <div key={index} className="flex items-center justify-center flex-col">
            
              <div className="flex items-center justify-center flex-col">
                <h3 className="text-2xl">{item.name}</h3>
                <p className='text-sm mt-[5px] w-[300px]'>{item.item}</p>
              </div>
            </div>
          )
        })
      }
    </div>

    </div>


    </div>
  </div>
</div>


<div style={{backgroundImage:'url("/Bg (2).png")',backgroundSize:'cover',backgroundRepeat:'no-repeat'}} className="h-[350px] w-[100%] mt-[50px] relative px-3">

  <div className="flex flex-col items-center justify-center text-white">
    <div><h1 className="text-center mt-[50px] font-bold text-2xl">Team Member</h1>
    <p className=' md:w-[450px] mt-[20px] text-center'>hLoreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhr sit amet, consectur adipiscing elit. Leo augue nibh</p>
    
    </div>


    <div className='grid grid-cols-2 md:grid-cols-4 gap-[20px] mt-[100px]'>
      {
        members.map((item,index)=>{
          return(
            <div className="bg-white h-[250px] shadow text-black" key={index}>
              <Image src={item.image} width={200} height={100} alt="icon"/>
              <div className='px-3 flex flex-col items-center justify-center mt-[2px]'>
                <h4 className="font-bold text-sm">{item.name}</h4>
                <span className='text-sm'>{item.pos}</span>
              </div>
              </div>
          )
        })
      }
    </div>



  </div>

<div className="absolute -top-[150px] right-0">
<Image src="/unsplash_1qnIDA6gZ1g.png" width={200} height={200} alt="icon"/>
</div>
</div>

<div className="flex items-center justify-center mt-[600px] flex-col md:mt-[300px]" >
<div>
        <h2 className="font-bold text-3xl text-center">Food Menu</h2>
        <p className=' md:w-[450px] mt-[20px] text-center text-sm'>hLoreum ipsuhLoreum ipsum door sit amet, c
       lit. Leo augue nibhr sit amet,
         consectur adipiscing elit. Leo augue nibh</p>
        </div>

        <div className="flex gap-[40px] mt-[30px] flex-col md:flex-row">
          <div className='flex flex-col gap-[40px] px-3'>
            {
              menu.map((item,index)=>{
                return (
                  <div key={index} className="flex justify-between">
                    <div>
                      <h3 className='font-bold text-sm'>{item.name}</h3>
                      <p className='text-sm'>{item.desc}</p></div>
                      <div className="font-bold text-green-700">{item.price}</div>
                  </div>
                )
              })
            }
          </div>



          <div className="flex gap-[40px] flex-col px-3 ">

          {
              menu.map((item,index)=>{
                return (
                  <div key={index} className="flex justify-between">
                    <div>
                    <h3 className='font-bold text-sm'>{item.name}</h3>
                      <p className='text-sm'>{item.desc}</p></div>
                      <div className="font-bold text-green-700">{item.price}</div>
                  </div>
                )
              })
            }
          </div>
        </div>
</div>



<div className="flex items-center justify-center mt-[100px]" >
  <div className="flex gap-[80px] flex-col md:flex-row px-4">
    <div>
        <h2>Testimonials</h2>
        <div>
        <h1 className="font-bold text-3xl">Customer Review</h1>
        <Image src="/Quotes.png" width={50} height={50} alt="icon"/>
        <p className=' md:w-[450px] mt-[20px] text-left text-sm'>hLoreum ipsuhLoreum ipsum door sit amet, c
        onsectur adipiscing elit. Leo augue nibhr sit amet,m door sit amet, consectur 
        adipiscing elit. Leo augue nibhr sit amet,hLoreum ipsum door sit amet, consectur adipiscing elit. Leo augue nibhr sit amet,
         consectur adipiscing elit. Leo augue nibh</p>
        </div>


        <div className="mt-[50px] flex gap-[20px]">
        <Image src="/Ellipse 2552.png" width={50} height={200} alt="icon"/>
        <div>
          <h3 className="text-sm font-bold">Ahmed Musa</h3>
          <p className="text-sm">Customer</p>
        </div>
        </div>
       
   

    </div>

    <div className="relative z-1">
    <Image src="/unsplash_oT7_v-I0hHg.png" width={500} height={200} alt="icon"/>
    <div className="bg-white shadow w-[340px] h-[150px] z-5 absolute -left-[50px] -bottom-[30px] rounded-md p-4">
      <div className='font-bold text-sm flex justify-between mb-[15px]'>
        <h2 className='font-bold text-sm'>Order now</h2>
        <h3 className='font-bold text-sm'>#980.10</h3>
      </div>
    <Image src="/Star.png" width={100} height={200} alt="icon"/>
    <p className=' w-[250px] mt-[10px] text-left text-sm'>hLoreum ipsuhLoreum ipsum door sit amet, c
        onsectur adipiscing elit. Leo augue nibhr sit amet,m
         Leo augue nibh</p>
    </div>
    </div>
  </div>
</div>

<div className="flex items-center justify-center mt-[100px] flex-col" >

  <div>
    <h1 className="text-3xl font-bold text-center mb-[40px]">We work with the best people</h1>
  </div>
  <div className="grid grid-cols-2 md:grid-cols-6 gap-[20px]">
  <Image src="/image 2.png" width={150} height={200} alt="icon"/>
  <Image src="/image 56.png" width={150} height={200} alt="icon"/>
  <Image src="/image 57.png" width={150} height={200} alt="icon"/>
   <Image src="/image 59.png" width={150} height={200} alt="icon"/>
   <Image src="/image 60 (1).png" width={150} height={200} alt="icon"/>
   <Image src="/image 60.png" width={150} height={200} alt="icon"/>
  </div>
</div>
      
    </>
  )
}
